---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-mongodb
  name: easytravel-mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-mongodb
    spec:
      containers:
      - image: dynatrace/easytravel-mongodb:latest
        imagePullPolicy: "Always"
        name: easytravel-mongodb
        ports:
        - containerPort: 27017
        - containerPort: 28017
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-mongodb
  name: easytravel-mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  - name: "28017"
    port: 28017
    targetPort: 28017
  selector:
    io.kompose.service: easytravel-mongodb
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-backend
  name: easytravel-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-backend
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Djava.security.egd=file:/dev/./urandom
        - name: ET_DATABASE_LOCATION
          value: easytravel-mongodb:27017
        image: dynatrace/easytravel-backend:latest
        imagePullPolicy: "Always"
        name: easytravel-backend
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /services/JourneyService/getLocations
            port: 8080
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 240
          successThreshold: 1
          timeoutSeconds: 1  
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-backend
  name: easytravel-backend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30687
  selector:
    io.kompose.service: easytravel-backend
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-frontend
  name: easytravel-frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: easytravel-frontend
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=APM -Xmx525m -Djava.security.egd=file:/dev/./urandom
        - name: ET_BACKEND_URL
          value: http://easytravel-backend:8080
        image: dynatrace/easytravel-frontend:latest
        imagePullPolicy: "Always"
        name: easytravel-frontend
        ports:
        - containerPort: 8080
        resources: {}
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 60
          initialDelaySeconds: 240
          successThreshold: 1
          timeoutSeconds: 1
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: easytravel-frontend
  name: easytravel-frontend
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30683
  selector:
    io.kompose.service: easytravel-frontend
  type: NodePort
status:
  loadBalancer: {}
