apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytravel-loadgen
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: easytravel-loadgen
    spec:
      containers:
      - env:
        - name: ET_APM_SERVER_DEFAULT
          value: APM
        - name: ET_FRONTEND_URL
          value: http://easytravel-frontend:8080
        - name: ET_PROBLEMS
          value: BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox
        image: dynatrace/easytravel-loadgen:latest
        imagePullPolicy: Always
        name: easytravel-loadgen
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-loadgen-rest
  namespace: easytravel
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    app: easytravel-loadgen
  type: LoadBalancer
status:
  loadBalancer: {}