apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: loadgen
    spec:
      containers:
      - env:
        - name: ET_APM_SERVER_DEFAULT
          value: APM
        - name: ET_FRONTEND_URL
          value: http://easytravel-frontend:8080
        - name: ET_PROBLEMS
          value: BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox
        image: dynatrace/easytravel-loadgen:latest
        imagePullPolicy: Always
        name: loadgen
        resources: {}
      restartPolicy: Always
status: {}